### ISSUE TITLE
Command Line Code Generation

### ISSUE THREAD

**Issue by kroeders** [categorizeus/categorizeus#23]
As I'm blessed to be developing without eclipse right now, getters and setters are about to cause a rage quit for the day - this is the part of java everyone else hates, been spoiled too long

**Comment by keefe** [comment]
this is working for getter/setter will tide me over until I get to eclipse again
ubuntu@ip-172-31-8-41:~/javagen$ git remote show origin
* remote origin
  Fetch URL: https://github.com/cym13/javagen.git
  Push  URL: https://github.com/cym13/javagen.git
  HEAD branch: master
  Remote branch:
    master tracked
  Local branch configured for 'git pull':
    master merges with remote master
  Local ref configured for 'git push':
    master pushes to master (up to date)
ubuntu@ip-172-31-8-41:~/javagen$ git diff
diff --git a/javagen b/javagen
index be8c184..c57a2f5 100755
--- a/javagen
+++ b/javagen
@@ -37,7 +37,7 @@ def constructor(classname, att_list):
     return text
 
 def definition(att, att_type):
-    return "    private %s %s;" % (att_type, att)
+    return "    private %s %s;" % (att_type[:], att[:])
 
 
 def getter(att, att_type):
@@ -82,14 +82,8 @@ def main():
     if class_name:
         output.append(gen_class(class_name))
 
-    for att, att_type in zip(att_name, att_type):
-        output.append(definition(att, att_type))
-
     output.append("")
 
-    if class_name:
-        output.append(constructor(class_name, list(zip(att_name,att_type))))
-
     for att, att_type in zip(att_name, att_type):
         if getters:
             output.append(getter(att, att_type))
ubuntu@ip-172-31-8-41:~/javagen$
